-- CreateEnum
CREATE TYPE "CandidateStatus" AS ENUM ('ACTIVE', 'REJECTED', 'SHORTLISTED', 'CONTACTED');

-- CreateEnum
CREATE TYPE "FeedbackAction" AS ENUM ('REJECT', 'SHORTLIST', 'UNDO');

-- CreateEnum
CREATE TYPE "RejectionReason" AS ENUM ('LOW_ACTIVITY', 'WRONG_TECH_STACK', 'JUNIOR_LEVEL', 'LOW_SCORE', 'WRONG_LOCATION', 'NO_RECENT_ACTIVITY', 'OTHER');

-- AlterTable
ALTER TABLE "candidates" ADD COLUMN     "status" "CandidateStatus" NOT NULL DEFAULT 'ACTIVE';

-- CreateTable
CREATE TABLE "candidate_feedbacks" (
    "id" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "action" "FeedbackAction" NOT NULL,
    "reason" "RejectionReason",
    "notes" TEXT,
    "snapshot" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "candidate_feedbacks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rejection_rules" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "conditions" JSONB NOT NULL,
    "confidence" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "hitCount" INTEGER NOT NULL DEFAULT 0,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "rejection_rules_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "candidate_feedbacks_action_idx" ON "candidate_feedbacks"("action");

-- CreateIndex
CREATE INDEX "candidate_feedbacks_reason_idx" ON "candidate_feedbacks"("reason");

-- CreateIndex
CREATE INDEX "candidate_feedbacks_candidateId_idx" ON "candidate_feedbacks"("candidateId");

-- CreateIndex
CREATE INDEX "candidate_feedbacks_createdAt_idx" ON "candidate_feedbacks"("createdAt");

-- CreateIndex
CREATE INDEX "rejection_rules_enabled_idx" ON "rejection_rules"("enabled");

-- CreateIndex
CREATE INDEX "rejection_rules_confidence_idx" ON "rejection_rules"("confidence" DESC);

-- CreateIndex
CREATE INDEX "candidates_status_idx" ON "candidates"("status");

-- AddForeignKey
ALTER TABLE "candidate_feedbacks" ADD CONSTRAINT "candidate_feedbacks_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "candidates"("id") ON DELETE CASCADE ON UPDATE CASCADE;
