export type CandidateStatus = 'ACTIVE' | 'REJECTED' | 'SHORTLISTED' | 'CONTACTED';

export type RejectionReason =
  | 'LOW_ACTIVITY'
  | 'WRONG_TECH_STACK'
  | 'JUNIOR_LEVEL'
  | 'LOW_SCORE'
  | 'WRONG_LOCATION'
  | 'NO_RECENT_ACTIVITY'
  | 'OTHER';

export const REJECTION_REASON_LABELS: Record<RejectionReason, string> = {
  LOW_ACTIVITY: '활동량 부족',
  WRONG_TECH_STACK: '기술 스택 불일치',
  JUNIOR_LEVEL: '경력 수준 부족',
  LOW_SCORE: '점수 낮음',
  WRONG_LOCATION: '위치 부적합',
  NO_RECENT_ACTIVITY: '최근 활동 없음',
  OTHER: '기타',
};

export interface RejectionStats {
  totalRejected: number;
  totalShortlisted: number;
  activeRules: number;
  reasonDistribution: {
    reason: RejectionReason;
    count: number;
    percentage: number;
  }[];
  recentRejections: number;
}

export interface RuleCondition {
  field: string;
  operator: '<' | '>' | '<=' | '>=' | '=' | '!=' | 'in' | 'notIn' | 'contains';
  value: string | number | boolean | string[] | number[];
}

export interface RejectionRule {
  id: string;
  name: string;
  description: string | null;
  conditions: RuleCondition[];
  confidence: number;
  hitCount: number;
  enabled: boolean;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PatternAnalysis {
  field: string;
  operator: '<' | '>' | '=' | 'in';
  value: number | string | string[];
  confidence: number;
  hitCount: number;
  description: string;
}
