import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { FeedbackAction, Prisma } from '@prisma/client';
import { RuleCondition } from './dto/feedback.dto';

export interface PatternAnalysis {
  field: string;
  operator: '<' | '>' | '=' | 'in';
  value: number | string | string[];
  confidence: number;
  hitCount: number;
  description: string;
}

interface SnapshotData {
  totalScore: number | null;
  followers: number;
  publicRepos: number;
  totalCommits: number;
  company: string | null;
  location: string | null;
  primaryLanguage: string | null;
  sources: string[];
}

const MIN_SAMPLES_FOR_PATTERN = 5;
const MIN_CONFIDENCE_FOR_RULE = 0.7;

@Injectable()
export class RejectionLearningService {
  private readonly logger = new Logger(RejectionLearningService.name);

  constructor(private prisma: PrismaService) {}

  async analyzePatterns(): Promise<PatternAnalysis[]> {
    const rejections = await this.prisma.candidateFeedback.findMany({
      where: {
        action: FeedbackAction.REJECT,
        snapshot: { not: Prisma.DbNull },
      },
      select: { snapshot: true },
    });

    if (rejections.length < MIN_SAMPLES_FOR_PATTERN) {
      this.logger.log(
        `Not enough rejections for pattern analysis (${rejections.length}/${MIN_SAMPLES_FOR_PATTERN})`,
      );
      return [];
    }

    const snapshots = rejections
      .map((r) => r.snapshot as unknown as SnapshotData)
      .filter((s) => s !== null);

    const patterns: PatternAnalysis[] = [];

    const scorePattern = this.analyzeNumericThreshold(
      snapshots,
      'totalScore',
      'Score threshold',
    );
    if (scorePattern) patterns.push(scorePattern);

    const followerPattern = this.analyzeNumericThreshold(
      snapshots,
      'followers',
      'Follower threshold',
    );
    if (followerPattern) patterns.push(followerPattern);

    const repoPattern = this.analyzeNumericThreshold(
      snapshots,
      'publicRepos',
      'Repository count threshold',
    );
    if (repoPattern) patterns.push(repoPattern);

    const commitPattern = this.analyzeNumericThreshold(
      snapshots,
      'totalCommits',
      'Commit count threshold',
    );
    if (commitPattern) patterns.push(commitPattern);

    const languagePattern = this.analyzeCategoricalFrequency(
      snapshots,
      'primaryLanguage',
      'Common rejected language',
    );
    if (languagePattern) patterns.push(languagePattern);

    const sourcePattern = this.analyzeArrayFrequency(
      snapshots,
      'sources',
      'Common rejected source',
    );
    if (sourcePattern) patterns.push(sourcePattern);

    this.logger.log(
      `Analyzed ${snapshots.length} rejections, found ${patterns.length} patterns`,
    );

    return patterns.sort((a, b) => b.confidence - a.confidence);
  }

  async generateRulesFromPatterns(): Promise<number> {
    const patterns = await this.analyzePatterns();

    const highConfidencePatterns = patterns.filter(
      (p) => p.confidence >= MIN_CONFIDENCE_FOR_RULE,
    );

    let created = 0;

    for (const pattern of highConfidencePatterns) {
      const existingRule = await this.prisma.rejectionRule.findFirst({
        where: {
          autoGenerated: true,
          name: { contains: pattern.field },
        },
      });

      if (existingRule) {
        await this.prisma.rejectionRule.update({
          where: { id: existingRule.id },
          data: {
            conditions: [
              {
                field: pattern.field,
                operator: pattern.operator,
                value: pattern.value,
              },
            ] as unknown as Prisma.InputJsonValue,
            confidence: pattern.confidence,
            hitCount: pattern.hitCount,
          },
        });
      } else {
        await this.prisma.rejectionRule.create({
          data: {
            name: `Auto: ${pattern.description}`,
            description: `Automatically generated rule based on ${pattern.hitCount} rejections`,
            conditions: [
              {
                field: pattern.field,
                operator: pattern.operator,
                value: pattern.value,
              },
            ] as unknown as Prisma.InputJsonValue,
            confidence: pattern.confidence,
            hitCount: pattern.hitCount,
            autoGenerated: true,
            enabled: pattern.confidence >= 0.8,
          },
        });
        created++;
      }
    }

    this.logger.log(
      `Generated ${created} new rules from ${highConfidencePatterns.length} high-confidence patterns`,
    );

    return created;
  }

  private analyzeNumericThreshold(
    snapshots: SnapshotData[],
    field: keyof SnapshotData,
    description: string,
  ): PatternAnalysis | null {
    const values = snapshots
      .map((s) => s[field] as number | null)
      .filter((v): v is number => v !== null && typeof v === 'number');

    if (values.length < MIN_SAMPLES_FOR_PATTERN) {
      return null;
    }

    values.sort((a, b) => a - b);

    const percentile25 = values[Math.floor(values.length * 0.25)];
    const percentile75 = values[Math.floor(values.length * 0.75)];
    const median = values[Math.floor(values.length * 0.5)];

    const belowMedianCount = values.filter((v) => v <= median).length;
    const belowMedianRatio = belowMedianCount / values.length;

    if (belowMedianRatio >= 0.6) {
      const threshold = percentile75;
      const confidence = Math.min(belowMedianRatio, 0.95);

      return {
        field,
        operator: '<',
        value: Math.round(threshold),
        confidence,
        hitCount: belowMedianCount,
        description: `${description} < ${Math.round(threshold)}`,
      };
    }

    return null;
  }

  private analyzeCategoricalFrequency(
    snapshots: SnapshotData[],
    field: keyof SnapshotData,
    description: string,
  ): PatternAnalysis | null {
    const values = snapshots
      .map((s) => s[field] as string | null)
      .filter((v): v is string => v !== null && typeof v === 'string');

    if (values.length < MIN_SAMPLES_FOR_PATTERN) {
      return null;
    }

    const frequency = new Map<string, number>();
    for (const value of values) {
      frequency.set(value, (frequency.get(value) || 0) + 1);
    }

    const sortedEntries = [...frequency.entries()].sort((a, b) => b[1] - a[1]);

    if (sortedEntries.length === 0) {
      return null;
    }

    const [topValue, topCount] = sortedEntries[0];
    const ratio = topCount / values.length;

    if (ratio >= 0.3 && topCount >= MIN_SAMPLES_FOR_PATTERN) {
      return {
        field,
        operator: '=',
        value: topValue,
        confidence: Math.min(ratio + 0.2, 0.95),
        hitCount: topCount,
        description: `${description}: ${topValue}`,
      };
    }

    return null;
  }

  private analyzeArrayFrequency(
    snapshots: SnapshotData[],
    field: keyof SnapshotData,
    description: string,
  ): PatternAnalysis | null {
    const allValues: string[] = [];

    for (const snapshot of snapshots) {
      const value = snapshot[field];
      if (Array.isArray(value)) {
        allValues.push(...value);
      }
    }

    if (allValues.length < MIN_SAMPLES_FOR_PATTERN) {
      return null;
    }

    const frequency = new Map<string, number>();
    for (const value of allValues) {
      frequency.set(value, (frequency.get(value) || 0) + 1);
    }

    const sortedEntries = [...frequency.entries()].sort((a, b) => b[1] - a[1]);

    if (sortedEntries.length === 0) {
      return null;
    }

    const [topValue, topCount] = sortedEntries[0];
    const ratio = topCount / snapshots.length;

    if (ratio >= 0.4 && topCount >= MIN_SAMPLES_FOR_PATTERN) {
      return {
        field,
        operator: 'in',
        value: [topValue],
        confidence: Math.min(ratio, 0.95),
        hitCount: topCount,
        description: `${description}: ${topValue}`,
      };
    }

    return null;
  }
}
