package com.peopleminer.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "rejection_rules", indexes = {
    @Index(name = "idx_rejection_rules_enabled", columnList = "enabled"),
    @Index(name = "idx_rejection_rules_confidence", columnList = "confidence DESC")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RejectionRule {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb", nullable = false)
    private List<RuleCondition> conditions;

    @Builder.Default
    private double confidence = 0;

    @Builder.Default
    private int hitCount = 0;

    @Builder.Default
    private boolean enabled = true;

    @Builder.Default
    private boolean autoGenerated = false;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class RuleCondition {
        private String field;
        private String operator;
        private Object value;
    }
}
